@startuml

class Component {
- name: String
- AvgAmount: double
- Unit: String
}


enum DataType{
- Foundation: String
- Experimental: String
}

class Search{
- searchedName: String
- DataType: DataType
- foodCategory: String
- FDC_id: int
- NDBNumber: int
- footNote: String
- FDC_Published: DateTime
}




@enduml